name: transfert-server-log

on:
  schedule:
  - cron: "0/5 * * * *"
    
jobs:
  stale:
    runs-on: ubuntu-latest

    steps:
    - name: Instalation des dépendances
      run: apt-get update -qq && apt-get install -y -qq lftp
    - name: Récupération du fichier
      run: lftp sftp://${{ secrets.SFTP_USER }}:${{ secrets.SFTP_PWD }}@${{ secrets.SFTP_HOST }}:${{ secrets.SFTP_PORT }} -e "get /log.csv -o /log.csv; delete /log.csv; quit"
    - name: Exportation du fichier
      run: lftp ftp://${{ secrets.FTP_USER }}:${{ secrets.FTP_PWD }}@${{ secrets.FTP_HOST }} -e "put -O /log.csv /log.csv; quit"
